apiVersion: v1
kind: Service
metadata:
  name: collector-service
spec:
  type: LoadBalancer
  selector:
    app: collector-service
  ports:
    - protocol: TCP
      port: 8001   # Puerto del servicio
      targetPort: 8080 # Puerto del contenedor
      nodePort: 30008
