namespaceOverride: "mongodb"

architecture: replicaset

replicaSet:
  replicaCount: 3

auth:
  enabled: false

persistence:
  enabled: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  type: ClusterIP